feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false

server:
  port: 8080

country:
  banned:
    Denmark,England